name: commit lint
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Lint commit
        uses: wagoid/commitlint-github-action@v6.2.1
        with:
          configFile: './.commitlintrc.json'
